/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.modules.tagfilter;

import java.awt.Dimension;
import javax.swing.JFrame;


/**
 *
 * @author root
 */
public class TagFilterToolbar extends javax.swing.JPanel {
	//private static final Logger logger = Logger.getLogger(TagFilterToolbar.class.getName());
	private static TagFilterToolbar instance;
	private JFrame tagFilterConfigurationFrame;
	/**
	 * Creates new form TagFilterToolbar
	 */
	private TagFilterToolbar() {
		initComponents();
		customizeComponents();
	}
	
	public synchronized static TagFilterToolbar getInstance() {
        if (instance == null) {
            instance = new TagFilterToolbar();
        }
        return instance;
    }

    private void customizeComponents() {
        
    }
	
    private void openTagFilter(){
	    if(tagFilterConfigurationFrame == null)
	    {
		tagFilterConfigurationFrame = new JFrame(org.openide.util.NbBundle.getMessage(TagFilterToolbar.class, "TagFilterConfig"));
		tagFilterConfigurationFrame.setPreferredSize(new Dimension(630, 400));
		tagFilterConfigurationFrame.add(new TagFilterConfiguration());
		tagFilterConfigurationFrame.pack();
	    }
	    tagFilterConfigurationFrame.setVisible(true);
    }

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();

                setOpaque(false);
                setPreferredSize(new java.awt.Dimension(102, 28));

                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/sleuthkit/autopsy/modules/tagfilter/icon_filter.png"))); // NOI18N
                org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(TagFilterToolbar.class, "TagFilterToolbar.jButton1.text")); // NOI18N
                jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
                jButton1.setBorderPainted(false);
                jButton1.setContentAreaFilled(false);
                jButton1.setOpaque(false);
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                openTagFilter();
        }//GEN-LAST:event_jButton1ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        // End of variables declaration//GEN-END:variables
}
